open_all_shutters:
  name: Open all shutters
  description: Open all shutters connected to the Mediola Gateway

close_all_shutters:
  name: Close all shutters
  description: Close all shutters connected to the Mediola Gateway

stop_all_shutters:
  name: Stop all shutters
  description: Stop all moving shutters connected to the Mediola Gateway